services:
    vpsmg9:
        public: true
        container_name: VPSMG9
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        ports:
            - 6080:6080
        environment: 
            - VNC_PASSWD=root
            - GEOMETRY=1280x768
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 2000m
          memory: 2048Mi
          storage:
            size: 500Mi
            class: standard
